---
apiVersion: v1
kind: Service
metadata:
  name: volume-secret-reader
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: volume-secret-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-secret-reader
  labels:
    app: volume-secret-reader
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: volume-secret-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: volume-secret-reader
    spec:
      containers:
        - name: volumesecretreader
          image: <YOUR_CONTAINER_REGISTRY>/volumesecretreader:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
          - name: DOTNET_USE_POLLING_FILE_WATCHER
            value: "true"
          ports:
            - containerPort: 80
              name: volume-secret
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
